name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: プルリクエスト情報を表示
        run: |
          echo "プルリクエストの作成者: ${{ github.event.pull_request.user.login }}"
          echo "プルリクエストのブランチ名: ${{ github.head_ref }}"
          echo "プルリクエストの番号: ${{ github.event.pull_request.number }}"

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
      - name: Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: TestBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
