name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: プルリクエスト情報を表示
        run: |
          echo "ユーザ名: ${{ github.actor }}"
          echo "プルリクエストのブランチ名: ${{ github.head_ref }}"
          echo "プルリクエストの番号: ${{ github.event.pull_request.number }}"
          echo "プルリクエストの作成者: ${{ github.event.pull_request.user.login }}"
